"""Account-owned local game managers and one-time legacy save import.

The HTTP adapter resolves an account from a server-side session before it
asks this registry for a game.  Account IDs are generated by ``AccountStore``;
browser-supplied names and deck IDs never choose a data directory.
"""

from __future__ import annotations

import json
import logging
import os
import re
import tempfile
import threading
import time
from pathlib import Path

from fireplace.arena.store import ArenaStore, default_state_path as legacy_arena_path

from .decks import DeckStore, default_state_path as legacy_deck_path
from .catalog import CardCatalog
from .match_archives import MatchArchiveStore


_ACCOUNT_ID = re.compile(r"^[0-9a-f]{32}$")
_LOG = logging.getLogger(__name__)


class LegacyImportError(ValueError):
    """The one-time legacy import cannot safely proceed."""


class AccountGameRegistry:
    """Give each account its own match, Arena run, and deck service."""

    def __init__(
        self,
        *,
        accounts: object,
        data_root: Path | None = None,
        seed: int | None = None,
        opponent: str = "radical",
        codex_model: str | None = None,
        codex_timeout: float | None = None,
        catalog: CardCatalog | None = None,
        idle_seconds: float = 300,
        legacy_decks: Path | None = None,
        legacy_arena: Path | None = None,
        room_registry: object | None = None,
    ) -> None:
        self.accounts = accounts
        configured_root = os.environ.get("TAVERNLAB_ACCOUNT_DATA_ROOT") or os.environ.get(
            "FIREPLACE_ACCOUNT_DATA_ROOT"
        )
        if data_root is not None:
            self.data_root = Path(data_root)
        elif configured_root:
            self.data_root = Path(configured_root).expanduser()
        else:
            self.data_root = Path(accounts.path).parent / "users"
        self.legacy_decks = Path(legacy_decks) if legacy_decks is not None else legacy_deck_path()
        self.legacy_arena = Path(legacy_arena) if legacy_arena is not None else legacy_arena_path()
        self.seed = seed
        self.opponent = opponent
        self.codex_model = codex_model
        self.codex_timeout = codex_timeout
        self.catalog = catalog if catalog is not None else CardCatalog()
        self.idle_seconds = float(idle_seconds)
        if room_registry is None:
            from .rooms import RoomRegistry

            room_registry = RoomRegistry(
                # RoomRegistry owns its ``rooms`` subdirectory.  Keep that
                # process-wide store beside account folders rather than
                # nesting ``rooms/rooms`` under the account root.
                data_root=self.data_root,
                seed=self.seed,
            )
            self._owns_rooms = True
        else:
            self._owns_rooms = False
        self.rooms = room_registry
        self._games: dict[str, object] = {}
        self._leases: dict[str, int] = {}
        self._last_used: dict[str, float] = {}
        self._eviction_retry_at: dict[str, float] = {}
        self._lock = threading.RLock()

    @staticmethod
    def _account_id(account_id: str) -> str:
        if not isinstance(account_id, str) or not _ACCOUNT_ID.fullmatch(account_id):
            raise ValueError("invalid account ID")
        return account_id

    def _directory(self, account_id: str) -> Path:
        return self.data_root / self._account_id(account_id)

    def for_account(self, account_id: str):
        """Return one reusable manager, isolated from every other account."""

        account_id = self._account_id(account_id)
        with self._lock:
            game = self._games.get(account_id)
            if game is None:
                from .server import WebGameManager

                folder = self._directory(account_id)
                archive_store = MatchArchiveStore(folder / "matches")
                game = WebGameManager(
                    seed=self.seed,
                    opponent=self.opponent,
                    codex_model=self.codex_model,
                    codex_timeout=self.codex_timeout,
                    arena_store=ArenaStore(folder / "arena-run.json"),
                    deck_store=DeckStore(folder / "decks.json"),
                    archive_store=archive_store,
                    catalog=self.catalog,
                )
                self._games[account_id] = game
            self._last_used[account_id] = time.monotonic()
            return game

    def acquire(self, account_id: str):
        """Lease a manager for one HTTP request so eviction cannot close it."""

        self.evict_idle()
        with self._lock:
            game = self.for_account(account_id)
            self._leases[account_id] = self._leases.get(account_id, 0) + 1
            return game

    def backend_for(self, account_id: str):
        """Return the facade used by authenticated HTTP requests."""

        account_id = self._account_id(account_id)
        manager = self.acquire(account_id)
        from .account_room import AccountRoomBackend

        return AccountRoomBackend(manager, account_id, self.rooms)

    def release(self, account_id: str) -> None:
        with self._lock:
            count = self._leases.get(account_id, 0)
            if count <= 1:
                self._leases.pop(account_id, None)
            else:
                self._leases[account_id] = count - 1
            self._last_used[account_id] = time.monotonic()

    def evict_idle(self) -> int:
        """Release idle managers while retaining every live match and request."""

        now = time.monotonic()
        retired = 0
        with self._lock:
            for account_id, game in list(self._games.items()):
                if self._leases.get(account_id, 0):
                    continue
                if now < self._eviction_retry_at.get(account_id, 0):
                    continue
                if now - self._last_used.get(account_id, now) < self.idle_seconds:
                    continue
                try:
                    if game.active is not None:
                        state = game.snapshot()
                        if state.get("outcome") is None:
                            continue
                        # Finalize an abandoned terminal Arena battle before
                        # closing its owner lock and releasing resources.
                        game.return_to_lobby({
                            "session_id": state["session_id"],
                            "revision": state["revision"],
                        })
                    # Keep this slot locked until Arena's owner lock is gone.
                    game.close()
                except Exception:
                    # A broken save in one account cannot prevent all other
                    # accounts from acquiring their own game. Keep the manager
                    # so an unrecorded Arena result is never silently lost.
                    self._eviction_retry_at[account_id] = now + 60
                    _LOG.exception("Cannot retire idle game for account %s", account_id)
                    continue
                del self._games[account_id]
                self._last_used.pop(account_id, None)
                self._eviction_retry_at.pop(account_id, None)
                retired += 1
        return retired

    def legacy_available(self, account_id: str | None = None) -> bool:
        """Whether old saves can be claimed by this account."""

        marker = self.data_root / ".legacy-imported.json"
        sources = [
            (self.legacy_decks, "decks.json"),
            (self.legacy_arena, "arena-run.json"),
        ]
        if marker.exists() or not any(source.is_file() for source, _ in sources):
            return False
        claim = self._legacy_claim()
        if claim is False or (claim is not None and account_id != claim):
            return False
        if account_id is None:
            return True
        folder = self._directory(account_id)
        for source, name in sources:
            target = folder / name
            if target.exists() and (
                not source.is_file() or target.read_bytes() != source.read_bytes()
            ):
                return False
        return True

    def _legacy_claim(self) -> str | bool | None:
        """Return the account that started import, or False for a broken claim."""

        path = self.data_root / ".legacy-import-claim.json"
        if not path.exists():
            return None
        try:
            account_id = json.loads(path.read_text(encoding="utf-8"))["account_id"]
            return self._account_id(account_id)
        except (OSError, ValueError, TypeError, KeyError):
            return False

    def import_legacy(self, account_id: str) -> dict[str, bool]:
        """Copy old global saves to a single empty account without removing them."""

        import fcntl

        account_id = self._account_id(account_id)
        with self._lock:
            self.data_root.mkdir(parents=True, exist_ok=True)
            lock_path = self.data_root / ".legacy-import.lock"
            with lock_path.open("a+b") as lock_stream:
                fcntl.flock(lock_stream.fileno(), fcntl.LOCK_EX)
                try:
                    return self._import_legacy_locked(account_id)
                finally:
                    fcntl.flock(lock_stream.fileno(), fcntl.LOCK_UN)

    def _import_legacy_locked(self, account_id: str) -> dict[str, bool]:
        marker = self.data_root / ".legacy-imported.json"
        if marker.exists():
            raise LegacyImportError("legacy saves were already imported")
        claim = self._legacy_claim()
        if claim is False:
            raise LegacyImportError("legacy import claim is invalid")
        if claim is not None and claim != account_id:
            raise LegacyImportError("legacy saves are claimed by another account")
        sources = [
            (self.legacy_decks, self._directory(account_id) / "decks.json"),
            (self.legacy_arena, self._directory(account_id) / "arena-run.json"),
        ]
        existing = [(source, target) for source, target in sources if source.is_file()]
        if not existing:
            raise LegacyImportError("no legacy saves are available")

        game = self._games.pop(account_id, None)
        if game is not None:
            if game.active is not None or self._leases.get(account_id, 0):
                self._games[account_id] = game
                raise LegacyImportError("finish the current match and pending requests before importing")
            game.close()
            self._last_used.pop(account_id, None)

        # Validate old data before copying.  Keep source files in place so a
        # failed import never consumes or rewrites the owner's only copy.
        if self.legacy_decks.is_file():
            DeckStore(self.legacy_decks).load()
        legacy_arena_store = ArenaStore(self.legacy_arena)
        if self.legacy_arena.is_file():
            legacy_arena_store.acquire_owner()
            try:
                legacy_arena_store.load()
            finally:
                legacy_arena_store.release_owner()

        source_data = [(source, target, source.read_bytes()) for source, target in existing]
        for source, target in sources:
            if not target.exists():
                continue
            data = next((value for old, _new, value in source_data if old == source), None)
            if data is None or target.read_bytes() != data:
                raise LegacyImportError("this account already has saved data")

        if claim is None:
            claim_path = self.data_root / ".legacy-import-claim.json"
            self._atomic_copy(
                json.dumps({"account_id": account_id}, separators=(",", ":")).encode("utf-8"),
                claim_path,
            )
            # _atomic_copy persists the claim before either save is copied.

        copied: list[Path] = []
        try:
            for _source, target, data in source_data:
                if target.exists():
                    continue  # A prior interrupted import published this exact file.
                target.parent.mkdir(parents=True, exist_ok=True)
                self._sync_directory(self.data_root)
                self._atomic_copy(data, target)
                copied.append(target)
            self._atomic_copy(
                json.dumps({"account_id": account_id}, separators=(",", ":")).encode("utf-8"),
                marker,
            )
        except Exception:
            for target in copied:
                target.unlink(missing_ok=True)
            raise
        return {"decks": self.legacy_decks.is_file(), "arena": self.legacy_arena.is_file()}

    @staticmethod
    def _atomic_copy(data: bytes, target: Path) -> None:
        fd, temporary = tempfile.mkstemp(prefix=".import-", dir=target.parent)
        try:
            with os.fdopen(fd, "wb") as stream:
                stream.write(data)
                stream.flush()
                os.fsync(stream.fileno())
            # Publishing through a hard link fails if another server has
            # created the destination meanwhile; importing must never
            # overwrite newly saved account data.
            os.link(temporary, target)
            AccountGameRegistry._sync_directory(target.parent)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)

    @staticmethod
    def _sync_directory(folder: Path) -> None:
        directory_fd = os.open(folder, os.O_RDONLY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)

    @staticmethod
    def error_payload(message: str) -> dict[str, str]:
        return {"mode": "lobby", "error": str(message)}

    def close(self) -> None:
        with self._lock:
            games = list(self._games.values())
            self._games.clear()
            self._leases.clear()
            self._last_used.clear()
            self._eviction_retry_at.clear()
        for game in games:
            game.close()
        if self._owns_rooms:
            self.rooms.close()


__all__ = ["AccountGameRegistry", "LegacyImportError"]
